import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { useMoralis } from "react-moralis";

export default function Home() {
  const router = useRouter();
  const { isInitialized } = useMoralis();

  useEffect(() => {
    router.push("/explore");
  });

  return (
    <div className="">
      <Head>
        <title>NFT MARKET</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
